#!/usr/bin/env python
# -*- coding: utf-8 -*-

from __future__ import print_function
import rospy
import numpy as np
from functions import *
from proyecto.msg import PersonConfig
from sensor_msgs.msg import LaserScan

class Lidar(object):
    def __init__(self):
        # Crear el suscriptor al tópico del LiDAR
        topic = 'scan'
        self.pub = rospy.Subscriber(topic, LaserScan, self.callback)
        self.lid = LaserScan()
        
        # Esperar 1 segundo
        rospy.sleep(1)

    def callback(self, msg):
        # Callback para el suscriptor
        self.lid = msg
        
    def get_med_ang(self):
        """ Retorna los valores de la medición y sus ángulos
            respectivos en el sistema del LiDAR
        """
        # Obtener los rangos medidos
        rangos = self.lid.ranges
        ang = np.linspace(0.0, np.pi, len(rangos)//2)
        #ang = np.linspace(0.0, np.pi*2, len(rangos))
        lim_r  = self.lid.range_max
        rangos = np.clip(rangos,0,lim_r)
        med = rangos[len(rangos)//2:len(rangos)]
        
        return med,ang


# Inicializar el nodo
rospy.init_node('nodo_person_config')

# Declarar del publicador
topic = 'person_config'
pub = rospy.Publisher(topic, PersonConfig, queue_size=10)

# Objeto que lee el escaneo
lidar = Lidar()

# Creación de una instancia (vacía) del mensaje
person_config_msg = PersonConfig()

# Asignar los valores de la medicion anterior
med_0, ang = lidar.get_med_ang()
pos_person0 = person_pos_xy(med_0, ang, 0, 0.5, -0.9)

# Tiempo de ejecución del bucle (en Hz)
freq = 100
dt = 1.0/freq
rate = rospy.Rate(freq)
t = 0.0

while not rospy.is_shutdown():

    # Lectura de los valores de medidas y angulos
    med, ang = lidar.get_med_ang()
    # Obtener la medicion filtrada
    med_f = lidar_filter(med,med_0,0.75)
    med_f = moving_average(med_f)
    # Actualizar la medicion anterior
    med_0 = med
    
    # Obtener la posición de la persona
    pos_person = person_pos_xy(med_f, ang, 0, 0.5, -0.9)
    #pos_person = lidar_filter(pos_person,pos_person0,0.2)
    #pos_person0 = pos_person
    
    # Asignar los valores en el mensaje
    person_config_msg.med        = np.round(med, 3)
    person_config_msg.med_f      = np.round(med_f, 3)
    person_config_msg.ang        = np.round(ang, 3)
    person_config_msg.pos_person = np.round(pos_person, 3)
    
    t = t + dt
    
    # Publicar el mensaje
    pub.publish(person_config_msg)
    
    # Esperar
    rate.sleep()
