#!/usr/bin/env python

from __future__ import print_function
import rospy
import numpy as np
from functions import *
from markers import *

from sensor_msgs.msg import JointState
from proyecto.msg import PersonConfig
from proyecto.msg import DistMin

pi = np.pi

class PosPerson(object):
    def __init__(self):
        topic    = 'person_config'
        self.pub = rospy.Subscriber(topic, PersonConfig, self.callback)
        self.pperson = PersonConfig()
        
    def callback(self, msg):
        self.pperson = msg
        
    def get_pperson(self):
        # Obtener la posicion de la capsula de la persona en el
        # espacio cartesiano
        pos = self.pperson.pos_person
        if len(pos) < 6:
            u = 0
        else:
            u = 1
        p_pos1 = np.array(pos[0:3])
        p_pos2 = np.array(pos[3:6])
        return p_pos1, p_pos2, u


class PosRobot(object):
    def __init__(self):
        topic    = 'first_robot/joint_states'
        self.pub = rospy.Subscriber(topic, JointState, self.callback)
        self.probot = JointState()
        
    def callback(self, msg):
        self.probot = msg
        
    def get_q(self):
        # Obtener la configuracion del robot
        q_rob = self.probot.position
        q = np.zeros(6)
        if len(q_rob) < 5:
            u = 0
        else:
            q[0] = q_rob[2]
            q[1] = q_rob[1]
            q[2] = q_rob[0]
            q[3] = q_rob[3]
            q[4] = q_rob[4]
            q[5] = q_rob[5]
            u = 1
        return q, u

class MinDist(object):
    def __init__(self):
        topic    = 'dist_min'
        self.pub = rospy.Subscriber(topic, DistMin, self.callback)
        self.dmin = DistMin()
        
    def callback(self, msg):
        self.dmin = msg
        
    def get_rs(self):
        r1 = self.dmin.r1
        r2 = self.dmin.r2
        if len(r1)<3 or len(r2)<3:
            u = 0
        else:
            u = 1
        return r1, r2, u

        
if __name__ == '__main__':    
    rospy.init_node('test_markers_node')
    
    pos_person = PosPerson()
    pos_robot  = PosRobot()
    min_dist   = MinDist()
    
    o1 = BallMarker(color['GREEN'])
    o2 = BallMarker(color['GREEN'])
    o3 = BallMarker(color['GREEN'])
    o4 = BallMarker(color['GREEN'])
    o5 = BallMarker(color['GREEN'])
    o6 = BallMarker(color['GREEN'])
    
    p1 = BallMarker(color['BLUE'])
    p2 = BallMarker(color['BLUE'])
    
    mr1 = BallMarker(color['RED'], scale=0.1)
    mr2 = BallMarker(color['RED'], scale=0.1)
    
    rate = rospy.Rate(20)

    while not rospy.is_shutdown():
        
        # Obtener la position en el espacio cartesiano de la 
        # persona y el robot
        p_pos1, p_pos2, u1 = pos_person.get_pperson()
        q, u2 = pos_robot.get_q()
        r1, r2, u3 = min_dist.get_rs()
        
        if u1==1 and u2==1 and u3 == 1: 
        
            pos = positions_robot(q)
            o1.xyz(pos[0:3,0])
            o2.xyz(pos[0:3,1])
            o3.xyz(pos[0:3,2])
            o4.xyz(pos[0:3,3])
            o5.xyz(pos[0:3,4])
            o6.xyz(pos[0:3,5])
            #print(pos[0:3,4])
            #print(pos[0:3,5])
            p1.xyz(p_pos1)
            p2.xyz(p_pos2)

            mr1.xyz(r1)
            mr2.xyz(r2)
        
        rate.sleep()
        
    
    
        

