#!/usr/bin/env python
"""
import os
import sys

if 'ROS_NAMESPACE' not in os.environ:
    # Default namespace if not set
    # Note, didn't need to check sys.argv for `__ns:=...`,
    # it seems __ns:= takes precidence over ROS_NAMESPACE

    os.environ['ROS_NAMESPACE'] = '/first_robot/arm_controller'
"""
import time
import roslib; roslib.load_manifest('ur_driver')
import rospy
import actionlib
import numpy as np
from control_msgs.msg import *
from trajectory_msgs.msg import *
from proyecto.msg import PersonConfig

pi = np.pi

class PosPerson(object):
    def __init__(self):
        topic    = 'person_config'
        self.pub = rospy.Subscriber(topic, PersonConfig, self.callback)
        self.pperson = PersonConfig()
        
    def callback(self, msg):
        self.pperson = msg
        
    def get_pperson(self):
        # Obtener la posicion de la capsula de la persona en el
        # espacio cartesiano
        pos = self.pperson.pos_person
        p_pos1 = np.array(pos[0:3])
        p_pos2 = np.array(pos[3:6])
        return p_pos1, p_pos2

if __name__ == '__main__':
    
    rospy.init_node("test1")
    
    
    pos_person = PosPerson()
    robot_client = actionlib.SimpleActionClient('/arm_controller/follow_joint_trajectory', FollowJointTrajectoryAction)

    print("Waiting for server...")
    robot_client.wait_for_server()
    print("Connected to server")

    joint_names = ['shoulder_pan_joint', 'shoulder_lift_joint', 'elbow_joint', 'wrist_1_joint', 'wrist_2_joint', 'wrist_3_joint']
    Q0 = [0.0, -1.0, 1.7, -2.2, -1.6, 0.0]
    Q0 = [-pi/2, 0.0, 0.0, -pi/2, -1.6, 0.0]
    Q1 = [-pi/2, -1.0, 1.7, -2.2, -1.6, 0.0]
    
    q1 = np.linspace(-pi/4,-3*pi/4,10)
    q2 = np.linspace(-0.5,-1.5,10)
    q3 = np.linspace(0,2,10)
    q4 = np.linspace(-pi,0,10)
    q5 = np.linspace(-pi/4,pi/4,10)
    q6 = np.linspace(-pi/4,pi/4,10)
    
    g = FollowJointTrajectoryGoal()
    g.trajectory = JointTrajectory()
    g.trajectory.joint_names = joint_names

    # Initial position
    g.trajectory.points = [ JointTrajectoryPoint(positions=Q0, velocities=[0]*6,time_from_start=rospy.Duration(2.0))]
    robot_client.send_goal(g)
    robot_client.wait_for_result()
    rospy.sleep(1)
    q_m = 0
    i = 0
    c = 0
    rate = rospy.Rate(10)
    while not rospy.is_shutdown():
        robot_client.cancel_goal()
        p_pos1, p_pos2 = pos_person.get_pperson()
        #print(p_pos1, p_pos2)
        q_m = q_m + 0.1
        Q = [q1[i], q2[i], q3[i], q4[i], q5[i], q6[i]]
        Q = [Q0[0], Q0[1], Q0[2], Q0[3]+q_m, Q0[4], Q0[5]]
        # Modification of the motion
        if c == 0:
            i = i + 1
            if i == 9:
                c = 1
        else:
            i = i - 1
            if i == 0:
                c = 0

	
        g.trajectory.points = [ JointTrajectoryPoint(positions=Q, velocities=[0]*6, time_from_start=rospy.Duration(0.1))]
        robot_client.send_goal(g)
        robot_client.wait_for_result()

        rate.sleep()

    robot_client.cancel_goal()
